name: Compile AutoHotkey Scripts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile all .ahk scripts in the root
        shell: pwsh
        run: |
          $compiler = ".\compiler\Ahk2Exe.exe"
          if (!(Test-Path $compiler)) {
            Write-Error "Ahk2Exe.exe not found at $compiler"
            exit 1
          }

          Get-ChildItem -Path . -Filter *.ahk | ForEach-Object {
            $input = $_.FullName
            $output = "$($_.BaseName).exe"
            & "$compiler" /in "$input" /out "$output"
          }
