name: Compile AutoHotkey Scripts

on:
  workflow_dispatch:

jobs:
  create_release:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile all .ahk scripts in the root
        shell: pwsh
        run: |
          $compiler = ".\compiler\Ahk2Exe.exe"
          if (!(Test-Path $compiler)) {
            Write-Error "Ahk2Exe.exe not found at $compiler"
            exit 1
          }

          New-Item -ItemType Directory -Path .\dist -Force | Out-Null

          Get-ChildItem -Path . -Filter *.ahk | ForEach-Object {
            $input = $_.FullName
            $output = "$($_.BaseName).exe"
            & "$compiler" /in "$input" /out ".\dist\$output"
          }
      
      - name: Create github release
        # You may pin to the exact commit or the version.
        # uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87
        uses: softprops/action-gh-release@v2.0.5
        with:
          tag_name: v1.0.0
          files: dist/*
          name: AutoHotkey Scripts
